name: Foxpost snapshot NEW

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Debug time
        run: |
          echo "=== DEBUG TIME ==="
          date
          echo "=================="

      - name: Test
        run: echo "Scheduler test"
``
